server:
  port: 8888
  address: localhost
  #address: 0.0.0.0
  contextPath: /

spring:
  data:
    mongodb:
      uri: mongodb://118.190.8.227:27017/kyeeplatform
      #uri: mongodb://mongo:27017/kyeeplatform
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:config/log4j2.xml
debug: false

hrp:
  url: https://f.kyee.com.cn/RightsSystem/

authority:
  admin: 40101,40000
  author: 40002,40000

file:
   address: /home/alan/workspace/kyee-2060/open-platform-frontend/img/